# Databricks notebook source
# MAGIC %md
# MAGIC # 04 · Constraints y columnas especiales (Python)
# MAGIC
# MAGIC Estas cosas **se definen en DDL**, no hay API de DataFrames para ellas. Así que
# MAGIC este notebook usa `spark.sql(...)` para crearlas y Python para probarlas.
# MAGIC
# MAGIC | Constraint | ¿Se aplica de verdad? |
# MAGIC |---|---|
# MAGIC | `NOT NULL` | **sí** |
# MAGIC | `CHECK` | **sí** |
# MAGIC | `PRIMARY KEY` | **no**, informativa |
# MAGIC | `FOREIGN KEY` | **no**, informativa |
# MAGIC
# MAGIC Delta **no** garantiza unicidad de PK. Si no quieres duplicados, es tu trabajo.

# COMMAND ----------

CATALOGO, ESQUEMA = "main", "demo_delta_py"
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOGO}.{ESQUEMA}")
spark.sql(f"USE CATALOG {CATALOGO}")
spark.sql(f"USE SCHEMA {ESQUEMA}")

# COMMAND ----------

spark.sql("""
    CREATE OR REPLACE TABLE pedidos (
      id       INT    NOT NULL,
      cliente  STRING NOT NULL,
      importe  DOUBLE,
      estado   STRING
    )
""")

spark.sql("ALTER TABLE pedidos ADD CONSTRAINT importe_positivo CHECK (importe > 0)")
spark.sql("""
    ALTER TABLE pedidos ADD CONSTRAINT estado_valido
      CHECK (estado IN ('nuevo','enviado','entregado','cancelado'))
""")

# COMMAND ----------

# MAGIC %md
# MAGIC Al añadir un `CHECK` a una tabla con datos, Databricks **valida lo que ya está**.
# MAGIC Si alguna fila lo incumple, el `ALTER` falla.

# COMMAND ----------

ok = spark.createDataFrame(
    [(1, "Ana", 100.0, "nuevo"), (2, "Bruno", 20.0, "enviado")],
    "id INT, cliente STRING, importe DOUBLE, estado STRING",
)
ok.write.mode("append").saveAsTable("pedidos")
display(spark.table("pedidos"))

# COMMAND ----------

def probar(df, etiqueta):
    """Intenta escribir y cuenta qué constraint la ha parado."""
    try:
        df.write.mode("append").saveAsTable("pedidos")
        print(f"{etiqueta}: escrito")
    except Exception as e:
        print(f"{etiqueta}: RECHAZADO -> {str(e)[:180]}")


probar(spark.createDataFrame([(3, None, 10.0, "nuevo")],
       "id INT, cliente STRING, importe DOUBLE, estado STRING"), "cliente NULL")

probar(spark.createDataFrame([(4, "Carla", -5.0, "nuevo")],
       "id INT, cliente STRING, importe DOUBLE, estado STRING"), "importe negativo")

probar(spark.createDataFrame([(5, "Diego", 10.0, "inventado")],
       "id INT, cliente STRING, importe DOUBLE, estado STRING"), "estado inválido")

# COMMAND ----------

# Los CHECK viven en las propiedades de la tabla
display(spark.sql("SHOW TBLPROPERTIES pedidos"))

# COMMAND ----------

spark.sql("ALTER TABLE pedidos DROP CONSTRAINT estado_valido")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Columnas generadas
# MAGIC
# MAGIC Se calculan solas a partir de otras. Ventajas: no puedes olvidarlas ni meter un
# MAGIC valor incoherente, y el optimizador conoce la relación (puede podar por la
# MAGIC columna generada al filtrar por la base).
# MAGIC
# MAGIC Si en el `INSERT` das un valor, tiene que coincidir con el calculado o falla.

# COMMAND ----------

spark.sql("""
    CREATE OR REPLACE TABLE eventos (
      id   INT,
      ts   TIMESTAMP,
      dia  DATE GENERATED ALWAYS AS (CAST(ts AS DATE)),
      anio INT  GENERATED ALWAYS AS (YEAR(ts))
    )
""")

# Desde Python: el DataFrame NO lleva las columnas generadas
from pyspark.sql.functions import to_timestamp, col

df = spark.createDataFrame(
    [(1, "2026-01-15 10:30:00"), (2, "2026-02-20 18:45:00")], "id INT, ts STRING"
).select(col("id"), to_timestamp(col("ts")).alias("ts"))

df.write.mode("append").saveAsTable("eventos")
display(spark.table("eventos"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Columnas IDENTITY
# MAGIC
# MAGIC | Variante | Comportamiento |
# MAGIC |---|---|
# MAGIC | `GENERATED ALWAYS AS IDENTITY` | siempre la pone Delta; no puedes darle valor |
# MAGIC | `GENERATED BY DEFAULT AS IDENTITY` | la pone Delta salvo que tú des uno |
# MAGIC
# MAGIC Los valores son **únicos y crecientes, pero no consecutivos**: cada escritor
# MAGIC reserva un bloque y quedan huecos. No sirven para contar filas.

# COMMAND ----------

spark.sql("""
    CREATE OR REPLACE TABLE dim_producto (
      sk     BIGINT GENERATED ALWAYS AS IDENTITY,
      nombre STRING
    )
""")

spark.createDataFrame([("teclado",), ("raton",), ("monitor",)], "nombre STRING") \
    .write.mode("append").saveAsTable("dim_producto")

display(spark.table("dim_producto"))

# COMMAND ----------

spark.sql("""
    CREATE OR REPLACE TABLE dim_producto_def (
      sk     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
      nombre STRING
    )
""")

spark.sql("INSERT INTO dim_producto_def (nombre) VALUES ('teclado')")
spark.sql("INSERT INTO dim_producto_def (sk, nombre) VALUES (999, 'importado')")
spark.sql("INSERT INTO dim_producto_def (nombre) VALUES ('raton')")

display(spark.table("dim_producto_def").orderBy("sk"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## PK y FK: informativas
# MAGIC
# MAGIC Requieren `NOT NULL`. Se marcan `RELY` si quieres que el optimizador se fíe. Pero
# MAGIC nadie te impide insertar duplicados ni huérfanos.

# COMMAND ----------

spark.sql("""
    CREATE OR REPLACE TABLE dim_pais (
      codigo STRING NOT NULL,
      nombre STRING,
      CONSTRAINT pk_pais PRIMARY KEY (codigo) RELY
    )
""")

spark.createDataFrame(
    [("ES", "España"), ("PT", "Portugal"), ("ES", "España duplicada")],
    "codigo STRING, nombre STRING",
).write.mode("append").saveAsTable("dim_pais")

# Se ha insertado el duplicado: la PK no se aplica
display(spark.table("dim_pais").orderBy("codigo"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Si necesitas unicidad de verdad
# MAGIC
# MAGIC No hay constraint que te la dé. Las dos vías reales:
# MAGIC
# MAGIC 1. **`MERGE` sobre la clave** en vez de `append` (ver notebook 01).
# MAGIC 2. Un **`CHECK` no vale** para esto; lo que sí sirve es una comprobación de
# MAGIC    calidad que falle el job si aparecen duplicados.

# COMMAND ----------

dups = spark.sql("""
    SELECT codigo, count(*) AS n
    FROM dim_pais
    GROUP BY codigo
    HAVING count(*) > 1
""")

if dups.count() > 0:
    display(dups)
    print("Hay duplicados. En un job real esto sería un raise.")
