-- Databricks notebook source
-- MAGIC %md
-- MAGIC # 04 · Constraints y columnas especiales
-- MAGIC
-- MAGIC Lo importante aquí es **cuáles se aplican de verdad y cuáles no**:
-- MAGIC
-- MAGIC | Constraint | ¿Se aplica? |
-- MAGIC |---|---|
-- MAGIC | `NOT NULL` | **Sí**, rechaza la escritura |
-- MAGIC | `CHECK` | **Sí**, rechaza la escritura |
-- MAGIC | `PRIMARY KEY` | **No**. Es informativa (para el optimizador y la doc) |
-- MAGIC | `FOREIGN KEY` | **No**. Informativa |
-- MAGIC
-- MAGIC O sea: Delta **no** garantiza unicidad de la PK. Si necesitas que no haya
-- MAGIC duplicados, es cosa tuya (un `MERGE` deduplicado, ver notebook 01).

-- COMMAND ----------

USE CATALOG main;
USE SCHEMA demo_delta;

CREATE OR REPLACE TABLE pedidos (
  id       INT     NOT NULL,
  cliente  STRING  NOT NULL,
  importe  DOUBLE,
  estado   STRING
);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## NOT NULL

-- COMMAND ----------

INSERT INTO pedidos VALUES (1, 'Ana', 100.0, 'nuevo');

-- Descomenta: falla, `cliente` es NOT NULL
-- INSERT INTO pedidos VALUES (2, NULL, 50.0, 'nuevo');

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## CHECK
-- MAGIC
-- MAGIC Al añadir un `CHECK` a una tabla con datos, Databricks **valida las filas que
-- MAGIC ya están**. Si alguna lo incumple, el `ALTER` falla.

-- COMMAND ----------

ALTER TABLE pedidos ADD CONSTRAINT importe_positivo CHECK (importe > 0);

ALTER TABLE pedidos ADD CONSTRAINT estado_valido
  CHECK (estado IN ('nuevo', 'enviado', 'entregado', 'cancelado'));

-- COMMAND ----------

-- Descomenta: falla por el CHECK de estado
-- INSERT INTO pedidos VALUES (3, 'Bruno', 20.0, 'inventado');

INSERT INTO pedidos VALUES (3, 'Bruno', 20.0, 'enviado');
SELECT * FROM pedidos ORDER BY id;

-- COMMAND ----------

-- Los CHECK viven en las propiedades de la tabla
SHOW TBLPROPERTIES pedidos;

-- COMMAND ----------

ALTER TABLE pedidos DROP CONSTRAINT estado_valido;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Columnas generadas
-- MAGIC
-- MAGIC Se calculan solas a partir de otras columnas. Dos ventajas:
-- MAGIC
-- MAGIC 1. No puedes olvidarte de rellenarlas ni meter un valor incoherente.
-- MAGIC 2. El optimizador sabe la relación, así que un filtro sobre la columna base
-- MAGIC    puede podar particiones de la columna generada (*generated column pruning*).
-- MAGIC
-- MAGIC Si en el `INSERT` das un valor para la columna generada, tiene que coincidir
-- MAGIC con el calculado o la escritura falla.

-- COMMAND ----------

CREATE OR REPLACE TABLE eventos (
  id      INT,
  ts      TIMESTAMP,
  dia     DATE   GENERATED ALWAYS AS (CAST(ts AS DATE)),
  anio    INT    GENERATED ALWAYS AS (YEAR(ts))
);

-- No se mencionan `dia` ni `anio`: se calculan solas
INSERT INTO eventos (id, ts) VALUES
  (1, TIMESTAMP'2026-01-15 10:30:00'),
  (2, TIMESTAMP'2026-02-20 18:45:00');

SELECT * FROM eventos;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Columnas IDENTITY
-- MAGIC
-- MAGIC Autonuméricas, para claves subrogadas.
-- MAGIC
-- MAGIC | Variante | Comportamiento |
-- MAGIC |---|---|
-- MAGIC | `GENERATED ALWAYS AS IDENTITY` | siempre la pone Delta; no puedes insertar valor |
-- MAGIC | `GENERATED BY DEFAULT AS IDENTITY` | la pone Delta **salvo** que tú des uno |
-- MAGIC
-- MAGIC Los valores son **únicos y crecientes, pero NO consecutivos**: cada escritor
-- MAGIC reserva un bloque, así que quedan huecos. No los uses para contar filas.

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_producto (
  sk      BIGINT GENERATED ALWAYS AS IDENTITY,
  nombre  STRING
);

INSERT INTO dim_producto (nombre) VALUES ('teclado'), ('raton'), ('monitor');
SELECT * FROM dim_producto;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_producto_def (
  sk      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
  nombre  STRING
);

INSERT INTO dim_producto_def (nombre) VALUES ('teclado');
INSERT INTO dim_producto_def (sk, nombre) VALUES (999, 'importado');  -- aquí sí puedo
INSERT INTO dim_producto_def (nombre) VALUES ('raton');

SELECT * FROM dim_producto_def ORDER BY sk;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## PRIMARY KEY / FOREIGN KEY: informativas
-- MAGIC
-- MAGIC Requieren `NOT NULL` y hay que marcarlas `RELY` si quieres que el optimizador
-- MAGIC se fíe. Pero nadie te impide insertar duplicados.

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_pais (
  codigo  STRING NOT NULL,
  nombre  STRING,
  CONSTRAINT pk_pais PRIMARY KEY (codigo) RELY
);

INSERT INTO dim_pais VALUES ('ES', 'España'), ('PT', 'Portugal');

-- Esto NO falla, aunque 'ES' ya existe: la PK no se aplica
INSERT INTO dim_pais VALUES ('ES', 'España duplicada');

SELECT * FROM dim_pais ORDER BY codigo;

-- COMMAND ----------

CREATE OR REPLACE TABLE hechos_venta (
  id      INT NOT NULL,
  pais    STRING,
  importe DOUBLE,
  CONSTRAINT pk_venta PRIMARY KEY (id),
  CONSTRAINT fk_pais FOREIGN KEY (pais) REFERENCES dim_pais(codigo)
);

-- Tampoco falla: la FK es informativa
INSERT INTO hechos_venta VALUES (1, 'XX', 10.0);
SELECT * FROM hechos_venta;
